DROP TABLE CourseSurvey CASCADE CONSTRAINT;
DROP TABLE FreeText CASCADE CONSTRAINT;
DROP TABLE TrueFalseChoice CASCADE CONSTRAINT;
DROP TABLE ResponseSingleChoice CASCADE CONSTRAINT;
DROP TABLE Choice CASCADE CONSTRAINT;
DROP TABLE FreeTextQuestion CASCADE CONSTRAINT;
DROP TABLE TrueFalseQuestion CASCADE CONSTRAINT;
DROP TABLE SingleChoiceQustion CASCADE CONSTRAINT;
DROP TABLE Question CASCADE CONSTRAINT;
DROP TABLE Survey CASCADE CONSTRAINT;
DROP TABLE Admin CASCADE CONSTRAINT;
DROP TABLE Respondent CASCADE CONSTRAINT;
DROP TABLE SurveyCreator CASCADE CONSTRAINT;
DROP TABLE UserRecord CASCADE CONSTRAINT;
DROP TABLE Department CASCADE CONSTRAINT;

set termout on
set feedback on
prompt All the tables are deleted.
set termout off
set feedback off